# Generated by Django 5.0.4 on 2024-08-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communucation',
            name='message',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Mesajınız'),
        ),
    ]
