# Generated by Django 5.0.4 on 2024-08-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Başlık')),
                ('about', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Blogs')),
                ('author', models.CharField(blank=True, max_length=50, null=True, verbose_name='Yazar')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
