# Generated by Django 5.0.4 on 2024-08-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Çekirdek Türü'),
        ),
    ]
